/**
 * generated by Xtext 2.10.0
 */
package org.zot.syntax.zot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Temp Dep</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.zot.syntax.zot.TempDep#getFd <em>Fd</em>}</li>
 *   <li>{@link org.zot.syntax.zot.TempDep#getFps <em>Fps</em>}</li>
 *   <li>{@link org.zot.syntax.zot.TempDep#getFa <em>Fa</em>}</li>
 *   <li>{@link org.zot.syntax.zot.TempDep#getOpf <em>Opf</em>}</li>
 *   <li>{@link org.zot.syntax.zot.TempDep#getF <em>F</em>}</li>
 *   <li>{@link org.zot.syntax.zot.TempDep#getOpfn <em>Opfn</em>}</li>
 *   <li>{@link org.zot.syntax.zot.TempDep#getF1 <em>F1</em>}</li>
 *   <li>{@link org.zot.syntax.zot.TempDep#getI <em>I</em>}</li>
 * </ul>
 *
 * @see org.zot.syntax.zot.ZotPackage#getTempDep()
 * @model
 * @generated
 */
public interface TempDep extends EObject
{
  /**
   * Returns the value of the '<em><b>Fd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fd</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fd</em>' containment reference.
   * @see #setFd(TPFormula)
   * @see org.zot.syntax.zot.ZotPackage#getTempDep_Fd()
   * @model containment="true"
   * @generated
   */
  TPFormula getFd();

  /**
   * Sets the value of the '{@link org.zot.syntax.zot.TempDep#getFd <em>Fd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fd</em>' containment reference.
   * @see #getFd()
   * @generated
   */
  void setFd(TPFormula value);

  /**
   * Returns the value of the '<em><b>Fps</b></em>' containment reference list.
   * The list contents are of type {@link org.zot.syntax.zot.TPFormula}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fps</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fps</em>' containment reference list.
   * @see org.zot.syntax.zot.ZotPackage#getTempDep_Fps()
   * @model containment="true"
   * @generated
   */
  EList<TPFormula> getFps();

  /**
   * Returns the value of the '<em><b>Fa</b></em>' containment reference list.
   * The list contents are of type {@link org.zot.syntax.zot.TempDep}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fa</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fa</em>' containment reference list.
   * @see org.zot.syntax.zot.ZotPackage#getTempDep_Fa()
   * @model containment="true"
   * @generated
   */
  EList<TempDep> getFa();

  /**
   * Returns the value of the '<em><b>Opf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Opf</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opf</em>' attribute.
   * @see #setOpf(String)
   * @see org.zot.syntax.zot.ZotPackage#getTempDep_Opf()
   * @model
   * @generated
   */
  String getOpf();

  /**
   * Sets the value of the '{@link org.zot.syntax.zot.TempDep#getOpf <em>Opf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Opf</em>' attribute.
   * @see #getOpf()
   * @generated
   */
  void setOpf(String value);

  /**
   * Returns the value of the '<em><b>F</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>F</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>F</em>' containment reference.
   * @see #setF(TempDep)
   * @see org.zot.syntax.zot.ZotPackage#getTempDep_F()
   * @model containment="true"
   * @generated
   */
  TempDep getF();

  /**
   * Sets the value of the '{@link org.zot.syntax.zot.TempDep#getF <em>F</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F</em>' containment reference.
   * @see #getF()
   * @generated
   */
  void setF(TempDep value);

  /**
   * Returns the value of the '<em><b>Opfn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Opfn</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opfn</em>' attribute.
   * @see #setOpfn(String)
   * @see org.zot.syntax.zot.ZotPackage#getTempDep_Opfn()
   * @model
   * @generated
   */
  String getOpfn();

  /**
   * Sets the value of the '{@link org.zot.syntax.zot.TempDep#getOpfn <em>Opfn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Opfn</em>' attribute.
   * @see #getOpfn()
   * @generated
   */
  void setOpfn(String value);

  /**
   * Returns the value of the '<em><b>F1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>F1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>F1</em>' containment reference.
   * @see #setF1(TempDep)
   * @see org.zot.syntax.zot.ZotPackage#getTempDep_F1()
   * @model containment="true"
   * @generated
   */
  TempDep getF1();

  /**
   * Sets the value of the '{@link org.zot.syntax.zot.TempDep#getF1 <em>F1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F1</em>' containment reference.
   * @see #getF1()
   * @generated
   */
  void setF1(TempDep value);

  /**
   * Returns the value of the '<em><b>I</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>I</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>I</em>' attribute.
   * @see #setI(int)
   * @see org.zot.syntax.zot.ZotPackage#getTempDep_I()
   * @model
   * @generated
   */
  int getI();

  /**
   * Sets the value of the '{@link org.zot.syntax.zot.TempDep#getI <em>I</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I</em>' attribute.
   * @see #getI()
   * @generated
   */
  void setI(int value);

} // TempDep
