/*
 * generated by Xtext 2.10.0
 */
package org.zot.syntax.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.zot.syntax.ui.internal.SyntaxActivator;

public class ZotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SyntaxActivator.getInstance().getInjector("org.zot.syntax.Zot");
	}

}
