/*
 * generated by Xtext 2.10.0
 */
package org.zot.syntax


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ZotStandaloneSetup extends ZotStandaloneSetupGenerated {

	def static void doSetup() {
		new ZotStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
