/**
 * generated by Xtext 2.10.0
 */
package org.zot.syntax.zot.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.zot.syntax.zot.Formula;
import org.zot.syntax.zot.TempDep;
import org.zot.syntax.zot.ZotPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Temp Dep</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.zot.syntax.zot.impl.TempDepImpl#getFd <em>Fd</em>}</li>
 *   <li>{@link org.zot.syntax.zot.impl.TempDepImpl#getFps <em>Fps</em>}</li>
 *   <li>{@link org.zot.syntax.zot.impl.TempDepImpl#getFa <em>Fa</em>}</li>
 *   <li>{@link org.zot.syntax.zot.impl.TempDepImpl#getOpf <em>Opf</em>}</li>
 *   <li>{@link org.zot.syntax.zot.impl.TempDepImpl#getF <em>F</em>}</li>
 *   <li>{@link org.zot.syntax.zot.impl.TempDepImpl#getOpfn <em>Opfn</em>}</li>
 *   <li>{@link org.zot.syntax.zot.impl.TempDepImpl#getF1 <em>F1</em>}</li>
 *   <li>{@link org.zot.syntax.zot.impl.TempDepImpl#getI <em>I</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TempDepImpl extends MinimalEObjectImpl.Container implements TempDep
{
  /**
   * The cached value of the '{@link #getFd() <em>Fd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFd()
   * @generated
   * @ordered
   */
  protected Formula fd;

  /**
   * The cached value of the '{@link #getFps() <em>Fps</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFps()
   * @generated
   * @ordered
   */
  protected EList<Formula> fps;

  /**
   * The cached value of the '{@link #getFa() <em>Fa</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFa()
   * @generated
   * @ordered
   */
  protected EList<TempDep> fa;

  /**
   * The default value of the '{@link #getOpf() <em>Opf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpf()
   * @generated
   * @ordered
   */
  protected static final String OPF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOpf() <em>Opf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpf()
   * @generated
   * @ordered
   */
  protected String opf = OPF_EDEFAULT;

  /**
   * The cached value of the '{@link #getF() <em>F</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getF()
   * @generated
   * @ordered
   */
  protected TempDep f;

  /**
   * The default value of the '{@link #getOpfn() <em>Opfn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpfn()
   * @generated
   * @ordered
   */
  protected static final String OPFN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOpfn() <em>Opfn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpfn()
   * @generated
   * @ordered
   */
  protected String opfn = OPFN_EDEFAULT;

  /**
   * The cached value of the '{@link #getF1() <em>F1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getF1()
   * @generated
   * @ordered
   */
  protected TempDep f1;

  /**
   * The default value of the '{@link #getI() <em>I</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getI()
   * @generated
   * @ordered
   */
  protected static final int I_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getI() <em>I</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getI()
   * @generated
   * @ordered
   */
  protected int i = I_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TempDepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ZotPackage.Literals.TEMP_DEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Formula getFd()
  {
    return fd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFd(Formula newFd, NotificationChain msgs)
  {
    Formula oldFd = fd;
    fd = newFd;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ZotPackage.TEMP_DEP__FD, oldFd, newFd);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFd(Formula newFd)
  {
    if (newFd != fd)
    {
      NotificationChain msgs = null;
      if (fd != null)
        msgs = ((InternalEObject)fd).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ZotPackage.TEMP_DEP__FD, null, msgs);
      if (newFd != null)
        msgs = ((InternalEObject)newFd).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ZotPackage.TEMP_DEP__FD, null, msgs);
      msgs = basicSetFd(newFd, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ZotPackage.TEMP_DEP__FD, newFd, newFd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Formula> getFps()
  {
    if (fps == null)
    {
      fps = new EObjectContainmentEList<Formula>(Formula.class, this, ZotPackage.TEMP_DEP__FPS);
    }
    return fps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<TempDep> getFa()
  {
    if (fa == null)
    {
      fa = new EObjectContainmentEList<TempDep>(TempDep.class, this, ZotPackage.TEMP_DEP__FA);
    }
    return fa;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getOpf()
  {
    return opf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOpf(String newOpf)
  {
    String oldOpf = opf;
    opf = newOpf;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ZotPackage.TEMP_DEP__OPF, oldOpf, opf));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TempDep getF()
  {
    return f;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetF(TempDep newF, NotificationChain msgs)
  {
    TempDep oldF = f;
    f = newF;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ZotPackage.TEMP_DEP__F, oldF, newF);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setF(TempDep newF)
  {
    if (newF != f)
    {
      NotificationChain msgs = null;
      if (f != null)
        msgs = ((InternalEObject)f).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ZotPackage.TEMP_DEP__F, null, msgs);
      if (newF != null)
        msgs = ((InternalEObject)newF).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ZotPackage.TEMP_DEP__F, null, msgs);
      msgs = basicSetF(newF, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ZotPackage.TEMP_DEP__F, newF, newF));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getOpfn()
  {
    return opfn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOpfn(String newOpfn)
  {
    String oldOpfn = opfn;
    opfn = newOpfn;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ZotPackage.TEMP_DEP__OPFN, oldOpfn, opfn));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TempDep getF1()
  {
    return f1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetF1(TempDep newF1, NotificationChain msgs)
  {
    TempDep oldF1 = f1;
    f1 = newF1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ZotPackage.TEMP_DEP__F1, oldF1, newF1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setF1(TempDep newF1)
  {
    if (newF1 != f1)
    {
      NotificationChain msgs = null;
      if (f1 != null)
        msgs = ((InternalEObject)f1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ZotPackage.TEMP_DEP__F1, null, msgs);
      if (newF1 != null)
        msgs = ((InternalEObject)newF1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ZotPackage.TEMP_DEP__F1, null, msgs);
      msgs = basicSetF1(newF1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ZotPackage.TEMP_DEP__F1, newF1, newF1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getI()
  {
    return i;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setI(int newI)
  {
    int oldI = i;
    i = newI;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ZotPackage.TEMP_DEP__I, oldI, i));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ZotPackage.TEMP_DEP__FD:
        return basicSetFd(null, msgs);
      case ZotPackage.TEMP_DEP__FPS:
        return ((InternalEList<?>)getFps()).basicRemove(otherEnd, msgs);
      case ZotPackage.TEMP_DEP__FA:
        return ((InternalEList<?>)getFa()).basicRemove(otherEnd, msgs);
      case ZotPackage.TEMP_DEP__F:
        return basicSetF(null, msgs);
      case ZotPackage.TEMP_DEP__F1:
        return basicSetF1(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ZotPackage.TEMP_DEP__FD:
        return getFd();
      case ZotPackage.TEMP_DEP__FPS:
        return getFps();
      case ZotPackage.TEMP_DEP__FA:
        return getFa();
      case ZotPackage.TEMP_DEP__OPF:
        return getOpf();
      case ZotPackage.TEMP_DEP__F:
        return getF();
      case ZotPackage.TEMP_DEP__OPFN:
        return getOpfn();
      case ZotPackage.TEMP_DEP__F1:
        return getF1();
      case ZotPackage.TEMP_DEP__I:
        return getI();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ZotPackage.TEMP_DEP__FD:
        setFd((Formula)newValue);
        return;
      case ZotPackage.TEMP_DEP__FPS:
        getFps().clear();
        getFps().addAll((Collection<? extends Formula>)newValue);
        return;
      case ZotPackage.TEMP_DEP__FA:
        getFa().clear();
        getFa().addAll((Collection<? extends TempDep>)newValue);
        return;
      case ZotPackage.TEMP_DEP__OPF:
        setOpf((String)newValue);
        return;
      case ZotPackage.TEMP_DEP__F:
        setF((TempDep)newValue);
        return;
      case ZotPackage.TEMP_DEP__OPFN:
        setOpfn((String)newValue);
        return;
      case ZotPackage.TEMP_DEP__F1:
        setF1((TempDep)newValue);
        return;
      case ZotPackage.TEMP_DEP__I:
        setI((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ZotPackage.TEMP_DEP__FD:
        setFd((Formula)null);
        return;
      case ZotPackage.TEMP_DEP__FPS:
        getFps().clear();
        return;
      case ZotPackage.TEMP_DEP__FA:
        getFa().clear();
        return;
      case ZotPackage.TEMP_DEP__OPF:
        setOpf(OPF_EDEFAULT);
        return;
      case ZotPackage.TEMP_DEP__F:
        setF((TempDep)null);
        return;
      case ZotPackage.TEMP_DEP__OPFN:
        setOpfn(OPFN_EDEFAULT);
        return;
      case ZotPackage.TEMP_DEP__F1:
        setF1((TempDep)null);
        return;
      case ZotPackage.TEMP_DEP__I:
        setI(I_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ZotPackage.TEMP_DEP__FD:
        return fd != null;
      case ZotPackage.TEMP_DEP__FPS:
        return fps != null && !fps.isEmpty();
      case ZotPackage.TEMP_DEP__FA:
        return fa != null && !fa.isEmpty();
      case ZotPackage.TEMP_DEP__OPF:
        return OPF_EDEFAULT == null ? opf != null : !OPF_EDEFAULT.equals(opf);
      case ZotPackage.TEMP_DEP__F:
        return f != null;
      case ZotPackage.TEMP_DEP__OPFN:
        return OPFN_EDEFAULT == null ? opfn != null : !OPFN_EDEFAULT.equals(opfn);
      case ZotPackage.TEMP_DEP__F1:
        return f1 != null;
      case ZotPackage.TEMP_DEP__I:
        return i != I_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (opf: ");
    result.append(opf);
    result.append(", opfn: ");
    result.append(opfn);
    result.append(", i: ");
    result.append(i);
    result.append(')');
    return result.toString();
  }

} //TempDepImpl
